### PR TITLE
Mark python-bitcoinlib 0.11 as compatible

### PR DESCRIPTION
**Pull request by mmilata**
Tried simple `ots stamp`, `ots verify` and `ots info` and they seem to work fine.

### CODE REVIEW

**Comment by jb55** [comment]
ACK dd8cfa5c057c665c6b5ba2dc689d81b91983c6bf, this is needed for bumping bitcoinlib in nixos: https://github.com/NixOS/nixpkgs/pull/89247 we patched it for now but ideally we wouldn't have to do that.

**Comment by petertodd** [comment]
Thanks!

**Comment by petertodd** [comment]
BTW, re: NixOS, if OTS moves to Rust what would help you guys package it?

**Comment by mmilata** [comment]
From my limited experience packaging Rust programs is really straightforward so I can't think of anything apart of including `Cargo.lock` in the sources.

**Comment by petertodd** [comment]
Great!

Do you need programs to be compilable on Rust stable? Or is Rust nightly ok too?

**Comment by mmilata** [comment]
I tried to grep around nixpkgs and all packages I've seen are compiled with stable (some using the `RUSTC_BOOTSTRAP` hack). Even though compiling with nightly [is possible on NixOS](https://nixos.org/nixpkgs/manual/#using-the-rust-nightlies-overlay) it seems that stable compiler is preferred for packages included in nixpkgs.

**Comment by petertodd** [comment]
Makes sense. 

For the opentimestamps client stable should be fine. I might want to use nightly for the server, but only because my proofmarshal stuff is likely to be nightly only until at least the ! type is stabilized.

**Pull request merged**
