### PR TITLE
added Catallaxy's server to the whitelist

### PR DESCRIPTION
**Pull request by cloutier**
I put no wildcard on purpose, we are not planning to ever run more than one server at Catallaxy.

### CODE REVIEW

**Comment by petertodd** [comment]
Hmm, I'm not sure that's a good idea; remember that the whitelist is really about *URI*'s, not necessarily servers.

Also, don't you have a LTC calendar? Right there that's a reason to have a wildcard. Probably better to whitelist `https://*.calendar.catallaxy.com`. Or perhaps even better, `https://*.calendar.ots.catallaxy.com`, in case you ever have a reason to have a calendar subdomain.

**Comment by cloutier** [comment]
I've changed it to `https://*.ots-calendar.catallaxy.com` so that it's future proof with our current naming scheme.

**Comment by petertodd** [comment]
Sure, that works!

**Comment by cloutier** [comment]
I've spoken with the team and they prefer that we use the pattern `https://ots.*.catallaxy.com`. I don't want to turn that into bikeshedding, so this is what we are going to commit to.

**Comment by petertodd** [comment]
This new whitelist sounds like a bad idea to me. The reason is that if you ever have a subdomain in the future that has any kind of "catch-all" functionality, or any ability for someone else to add subdomains too, an attacker can construct a timestamp proof that'll direct clients to match HTTP requests to it.

Similarly, suppose someone figures out some DoS attack along these lines: with a `*.ots-calendar.catallaxy.com` whitelist, at worse you can just blackhole all DNS requests for that one subdomain without affecting the rest of your site. With this proposed whitelist, you can't do that.

I wonder if there's some kind of best practices out there for this kind of thing? Maybe from the experience of NTP servers?

**Comment by cloutier** [comment]
I've been thinking a lot about this, and I'm starting to think I don't ever want my endpoint to change. I have already announced it as `https://ots.btc.catallaxy.com` and it should stay under this name forever. Google seems to be using simply `time.google.com` ¹, close in spirit to my original proposition.

 When I get to the point where my server is doing tens of millions of commitments per day (which is my goal), I am still going to have one endpoint, but with multiple servers with multiple IP, load balancers, and potentially a global database backend like CockroachDB, Google Spanner, a MongoDB cluster, or it would maybe make sense to roll my own sharding because of the nice scaling properties commitment hashes have (being deterministic, written once and uniformely distributed).

If I get a DoS attack on this endpoint, I could use a service like Cloudflare, or potentially just absorb it. 

If we feel ready to go ahead with Litecoin, it would make sense to just add another entry for that endpoint. This way, there would be no possibility of a rogue subdomain on our end.

We could bikeshed this to death, but in the end, it's a bit arbitrary.

1: https://developers.google.com/time/

**Comment by RCasatta** [comment]
When the calendar from eternitywall has been added to the ots default ones it was required a change in the DNS to be compliant. I am simply keeping the old dns pointing to the same IP for backward compatibility this could solve the issue caused by already have announced https://ots.btc.catallaxy.com

I would like the chosen name in the white list will be in the form https://*.calendar.catallaxy.com

**Comment by cloutier** [comment]
I still feel the same way, but since there is consensus on that other approach, let's move forward with that!

I've updated the whitelist to `https://*.calendar.catallaxy.com` and updated my servers to return as calendar urls: `https://btc.calendar.catallaxy.com` and `https://ltc.calendar.catallaxy.com`. I hereby commit to having those urls work indefinitely.

**Comment by petertodd** [comment]
> I hereby commit to having those urls work indefinitely.

Speaking of, I noticed that the domain `catallaxy.com` expires in only a few months. We should extend that as much as possible; I have `opentimestamps.org` paid up until 2023.

@RCasatta `eternitywall.com` also expires later this year!

**Comment by petertodd** [comment]
Also, are you running `otsd` behind a caching proxy server? I noticed you're running on Google cloud, but I have no idea how that infrastructure works. :)

**Comment by RCasatta** [comment]
@cloutier we are testing catallaxy calendar from opentimestamps.org , we need the cors headers to be set from the calendars to validate from the web.
If you use nginx is something like this:
```
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'POST GET';
```

Have a look at https://github.com/opentimestamps/opentimestamps-server/blob/master/contrib/nginx/a.pool.opentimestamps.org

**Comment by cloutier** [comment]
> Also, are you running otsd behind a caching proxy server? I noticed you're running on Google cloud, but I have no idea how that infrastructure works. :)

Nothing fancy yet! Simply a ubuntu VM, with apache as a caching reverse proxy. It's apache because I have worked a lot with it in the past and I'm really used to it. I don't mind changing if there is upside. Out of curiousity, where are you hosting alice, bob and finney?

> we are testing catallaxy calendar from opentimestamps.org , we need the cors headers to be set from the calendars to validate from the web.

Cors on ots.btc.catallaxy.com and  should be good to go now! 

> I noticed that the domain catallaxy.com expires in only a few months

Good catch, I'm forwarding this to the IT team.

**Comment by RCasatta** [comment]
> Cors on ots.btc.catallaxy.com and btc.calendar.catallaxy.com should be good to go now!

Thanks, could you add cors headers also to the ltc calendar server?

**Comment by cloutier** [comment]
> could you add cors headers also to the ltc calendar server?

Done!

**Comment by petertodd** [comment]
Looks like the calendar has been running fine, so I've gone ahead and merged this.

@cloutier Welcome to the team! :)

**Comment by petertodd** [comment]
@cloutier With the new ots-client release this is 100% live. :)

One issue: looks like the calendar/aggregator accepts connections via unencrypted HTTP. I think we should disable that to prevent mistakes.

**Comment by cloutier** [comment]
@petertodd Awesome!

I updated my apache config to redirect to https for `btc.calendar.catallaxy.com`. The previous config was only for `ots.btc.catallaxy.com`.

**Pull request merged**
